# Generated by Django 5.1 on 2024-09-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='pnr_number',
            field=models.CharField(default='UNKNOWN', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_images/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image_classification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
