# Generated by Django 5.1 on 2024-09-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_pnr_number_alter_complaint_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='image',
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_image',
            field=models.ImageField(blank=True, default='Not Classified', null=True, upload_to='complaint_images/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image_classification',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='pnr_number',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='sentiment',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
